spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/organizations/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/organizations/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            client-id: b9ac03e0-8b5e-4c38-865d-1c819e894e7a
            client-secret: RnS8Q~ni9LNfJlZfUrpR8Mshu91nfBwA4KI1XcBo
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login-success'
            scope: openid,profile
server:
  forward-headers-strategy: native
  port: 8080